### ISSUE TITLE
browser_extensions.plist Not Populating

### ISSUE THREAD

**Issue by walkintom** [tuxudo/browser_extensions#2]
Latest version of Browser Extensions module doesn't appear to be reporting on installed modules for Microsoft Edge. The two extensions I've tested with are not "default" extensions per se, but one is force installed by policy (ID: maapdampfadmflfaebmefdnekihlaabn) and the other is available to optionally install by policy (ID: oogbnpmeihfgnccdnmmlgicknopghhma) - not sure if this would have any affect on the module's script?

Both extensions are displayed in `~/Library/Application Support/Microsoft Edge/Default/Extensions`. Is there anything obvious I might've missed or can check?

![Screenshot 2022-07-19 at 17 23 56](https://user-images.githubusercontent.com/6242598/179800236-0a4f5f32-0a07-4401-add8-978d066609b2.png)

**Comment by tuxudo** [comment]
Having the extensions installed by policy should not change that. Do you have Firefox or Chrome installed onto that Mac? 

What is the output when you run `sudo /usr/local/munkireport/scripts/browser_extensions.py` on that Mac?

**Comment by walkintom** [comment]
No Firefox or Chrome, just Edge here.

No output, but it successfully writes the `browser_extensions.plist` file in `cache` but as the screenshot above, it's just empty.

**Comment by walkintom** [comment]
Tested on another machine and it was working fine, so as discussed it could just be something problematic with this test machine.
